// apps/web-react/src/components/Login/LoginForm.tsx
import { Form, Input, Button, message } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { login } from '@/apis/user'
import type { UserLogin } from '@en/common/user'
import md5 from 'md5'
import { useUserStore } from '@/stores/user'
import { useLogin } from '@/hooks/useLogin'

const LoginForm = () => {
    const [form] = Form.useForm<UserLogin>()
    const setUser = useUserStore((s) => s.setUser)
    const { hide } = useLogin()

    const handleLogin = async () => {
        const values = await form.validateFields()
        const res = await login({
            ...values,
            password: md5(values.password),
        })
        if (res.code === 200) {
            setUser(res.data)
            message.success('登录成功')
            hide()
        } else {
            message.error(res.message)
        }
    }

    return (
        <>
            <div className="mb-8">
                <h1 className="text-3xl font-bold text-gray-800 mb-2">欢迎回来</h1>
                <p className="text-gray-500 text-sm">请登录您的账户以继续</p>
            </div>

            <Form form={form} layout="vertical" size="large">
                <Form.Item
                    name="phone"
                    rules={[
                        { required: true, message: '请输入手机号' },
                        { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号' },
                    ]}
                >
                    <Input maxLength={11} prefix={<UserOutlined />} placeholder="请输入手机号" />
                </Form.Item>

                <Form.Item
                    name="password"
                    rules={[{ required: true, message: '请输入密码' }]}
                >
                    <Input.Password prefix={<LockOutlined />} placeholder="请输入密码" onPressEnter={handleLogin} />
                </Form.Item>

                <Form.Item>
                    <Button
                        type="primary"
                        block
                        className="h-12 text-base font-semibold"
                        onClick={handleLogin}
                    >
                        登录
                    </Button>
                </Form.Item>
            </Form>
        </>
    )
}

export default LoginForm

// apps/web/src/components/Login/LoginForm.vue
<template>
    <div class="mb-8">
        <h1 class="text-3xl font-bold text-gray-800 mb-2">欢迎回来</h1>
        <p class="text-gray-500 text-sm">请登录您的账户以继续</p>
    </div>

    <el-form ref="formRef" :model="form" :rules="rules" class="space-y-6">
        <el-form-item prop="phone">
            <el-input :maxlength="11" v-model="form.phone" placeholder="请输入手机号" size="large" class="h-12"
                :prefix-icon="User" />
        </el-form-item>

        <el-form-item prop="password">
            <el-input v-model="form.password" type="password" placeholder="请输入密码" size="large" class="h-12"
                :prefix-icon="Lock" show-password />
        </el-form-item>

        <el-form-item class="pt-4">
            <el-button type="primary" size="large"
                class="w-full h-12 text-base font-semibold bg-linear-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 border-0"
                @click="handleLogin">
                登录
            </el-button>
        </el-form-item>
    </el-form>
</template>


<script setup lang="ts">
import { ref, useTemplateRef, toRaw } from 'vue'
import { User, Lock } from '@element-plus/icons-vue'
import { login } from '@/apis/user' //登录的接口
import type { UserLogin } from '@en/common/user' //登录类型
import md5 from 'md5' //md5加密
import type { FormInstance } from 'element-plus'
import { ElMessage } from 'element-plus'
import { useUserStore } from '@/stores/user'
import { useLogin } from '@/hooks/useLogin'
const { hide } = useLogin()
const formRef = useTemplateRef<FormInstance>('formRef')
const userStore = useUserStore()
const form = ref<UserLogin>({
    phone: '',
    password: '',
})

const rules = {
    phone: [
        { required: true, message: '请输入手机号', trigger: 'blur' },
        { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号', trigger: 'blur' },
    ],
    password: [
        { required: true, message: '请输入密码', trigger: 'blur' },
    ],
}

const handleLogin = async () => {
    await formRef.value?.validate() //触发校验的
    console.log('form.value',form.value.password);
        
    const res = await login({
        ...toRaw(form.value),
        password: toRaw(md5(form.value.password))
    })
    if (res.code === 200) {
        userStore.setUser(res.data)
        ElMessage.success('登录成功')
        hide()
    } else {
        ElMessage.error(res.message)
    }
}
</script>
