// apps/web/src/views/Chat/components/Conversations.vue
<template>
    <div
        class="p-5 rounded-[5px] w-[256px] bg-purple-50 border border-right-1 border-t-0 border-b-0 border-l-0 border-gray-200">
        <div @click="changeActive(value)" :class="{ 'bg-purple-300': active === value.id }"
            class="rounded-[5px] p-2 transition-all duration-300" v-for="value in chatMode" :key="value.id">
            <div class="text-sm  cursor-pointer p-2 px-4 text-gray-700">
                {{ value.label }}
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import type { ChatModeList, ChatMode } from '@en/common/chat';
import { getChatMode } from '@/apis/chat';
const emits = defineEmits(['onGetRole'])
const chatMode = ref<ChatModeList>([]) //消息模式列表
const active = ref<string | null>(null) //当前激活的id
//切换消息模式
const changeActive = (value: ChatMode) => {
    active.value = value.id
    emits('onGetRole', value.role) //派发role
}
//获取消息模式列表
const getChatModeList = async () => {
    const res = await getChatMode()
    chatMode.value = res.data
    const firstItem = res.data[0]
    if (firstItem) {
        active.value = firstItem.id //默认选中第一个
        emits('onGetRole', firstItem.role) //派发role
    }
}
onMounted(() => {
    getChatModeList()
})
</script>

// apps/web-react/src/views/Chat/Conversations.tsx
import { useState, useEffect } from 'react'
import type { ChatModeList, ChatMode, ChatRoleType } from '@en/common/chat'
import { getChatMode } from '@/apis/chat'

interface Props {
    onGetRole: (role: ChatRoleType) => void
}

const Conversations = ({ onGetRole }: Props) => {
    const [chatMode, setChatMode] = useState<ChatModeList>([])
    const [active, setActive] = useState<string | null>(null)

    const changeActive = (value: ChatMode) => {
        setActive(value.id)
        onGetRole(value.role)
    }

    useEffect(() => {
        const getChatModeList = async () => {
            const res = await getChatMode()
            setChatMode(res.data)
            const firstItem = res.data[0]
            if (firstItem) {
                setActive(firstItem.id)
                onGetRole(firstItem.role)
            }
        }
        getChatModeList()
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    return (
        <div className="p-5 rounded-[5px] w-[256px] bg-purple-50 border-r border-gray-200">
            {chatMode.map((value) => (
                <div
                    key={value.id}
                    onClick={() => changeActive(value)}
                    className={`rounded-[5px] p-2 transition-all duration-300 ${active === value.id ? 'bg-purple-300' : ''}`}
                >
                    <div className="text-sm cursor-pointer p-2 px-4 text-gray-700">
                        {value.label}
                    </div>
                </div>
            ))}
        </div>
    )
}

export default Conversations
