// apps/web/src/layout/Profile/index.vue
<template>
    <section class="w-80 overflow-hidden rounded-[14px] bg-linear-to-b from-white/95 to-slate-50/95 backdrop-blur"
        aria-label="用户资料卡">
        <div class="flex items-center gap-3 px-4 pb-3 pt-3.5">
            <div class="grid size-11 shrink-0 place-items-center rounded-full border border-gray-200">
                <img class="size-10 rounded-full object-cover" :src="avatar" loading="lazy" />
            </div>

            <div class="min-w-0 flex-1">
                <div class="flex min-w-0 items-center gap-2">
                    <div class="flex flex-col gap-1">
                        <div class="truncate text-sm font-extrabold leading-5 text-slate-900" :title="displayName">
                            {{ displayName }}
                        </div>
                        <div v-if="bio" class="truncate text-xs leading-4 text-slate-500/90" :title="bio">
                            {{ bio }}
                        </div>
                    </div>
                </div>
                <div v-if="!isLoggedIn" class="mt-1 text-xs leading-4 text-slate-500/90">
                    登录后可同步词库进度与打卡数据
                </div>
            </div>
        </div>

        <div class="grid grid-cols-2 gap-2.5 px-4 pb-3 pt-2" v-if="isLoggedIn">
            <div class="rounded-xl border border-slate-900/5 bg-white/65 px-2.5 py-2.5">
                <div class="text-xs leading-4 text-slate-500/95">单词数量</div>
                <div class="mt-1 text-lg font-black leading-[22px] text-slate-900">
                    {{ userStore?.getUser?.wordNumber ?? 0 }}
                </div>
            </div>
            <div class="rounded-xl border border-amber-500/20 bg-amber-50/90 px-2.5 py-2.5">
                <div class="text-xs leading-4 text-slate-500/95">打卡天数</div>
                <div class="mt-1 text-lg font-black leading-[22px] text-slate-900">
                    {{ userStore?.getUser?.dayNumber ?? 0 }}
                </div>
            </div>
        </div>

        <div class="flex gap-2.5 border-t border-slate-900/5 bg-white/75 px-4 pb-3.5 pt-3">
            <button v-if="!isLoggedIn"
                class="h-9 flex-1 cursor-pointer rounded-[10px] border border-blue-600/25 bg-blue-600/10 text-[13px] font-extrabold text-blue-700 transition duration-150 hover:-translate-y-0.5 hover:shadow-[0_10px_16px_rgba(15,23,42,0.10)] active:translate-y-0 active:shadow-none motion-reduce:transition-none motion-reduce:hover:translate-y-0 motion-reduce:hover:shadow-none"
                type="button" @click="loginHandle">
                去登录
            </button>
            <template v-else>
                <button
                    class="h-9 flex-1 cursor-pointer rounded-[10px] border border-slate-900/10 bg-white/90 text-[13px] font-extrabold text-slate-900/90 transition duration-150 hover:-translate-y-0.5 hover:shadow-[0_10px_16px_rgba(15,23,42,0.10)] active:translate-y-0 active:shadow-none motion-reduce:transition-none motion-reduce:hover:translate-y-0 motion-reduce:hover:shadow-none"
                    type="button" @click="gotoPath('/setting/index')">
                    个人资料
                </button>
                <button
                    class="h-9 flex-1 cursor-pointer rounded-[10px] border border-red-500/20 bg-red-500/10 text-[13px] font-extrabold text-red-700 transition duration-150 hover:-translate-y-0.5 hover:shadow-[0_10px_16px_rgba(15,23,42,0.10)] active:translate-y-0 active:shadow-none motion-reduce:transition-none motion-reduce:hover:translate-y-0 motion-reduce:hover:shadow-none"
                    type="button" @click="logoutHandle">
                    退出登录
                </button>
            </template>
        </div>
    </section>
</template>

<script setup lang="ts">
import { computed } from 'vue' //引入计算属性
import { useRouter } from 'vue-router' //引入路由
import { useUserStore } from '@/stores/user' //引入用户信息
import { useAvatar } from '@/hooks/useAvatar'
import { useLogin } from '@/hooks/useLogin'
import { ElMessageBox } from 'element-plus'

const { login, logout } = useLogin()
const { avatar } = useAvatar()
const userStore = useUserStore() //初始化用户信息
const isLoggedIn = computed(() => !!userStore.getUser) //是否登录
const router = useRouter() //初始化路由
const bio = computed(() => userStore.getUser?.bio ?? '') //签名
const displayName = computed(() => userStore.getUser?.name ?? '游客') //用户名

//跳转页面
const gotoPath = (path: string) => {
    router.push(path)
}
//去登录
const loginHandle = () => {
    login()
}
//退出登录
const logoutHandle = () => {
    ElMessageBox.confirm('确定退出登录吗？', '提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning',
    }).then(() => {
        logout()
    })
}
</script>

// apps/web-react/src/layout/Profile.tsx
import { useNavigate } from 'react-router-dom'
import { Modal } from 'antd'
import { useUserStore } from '@/stores/user'
import { useAvatar } from '@/hooks/useAvatar'
import { useLogin } from '@/hooks/useLogin'

const Profile = () => {
    const user = useUserStore((s) => s.user)
    const { avatar } = useAvatar()
    const { login, logout } = useLogin()
    const navigate = useNavigate()
    const isLoggedIn = !!user
    const displayName = user?.name ?? '游客'
    const bio = user?.bio ?? ''

    const gotoPath = (path: string) => {
        navigate(path)
    }

    const loginHandle = () => {
        login().catch(() => {})
    }

    const logoutHandle = () => {
        Modal.confirm({
            title: '提示',
            content: '确定退出登录吗？',
            okText: '确定',
            cancelText: '取消',
            onOk: () => logout(),
        })
    }

    return (
        <section className="w-80 overflow-hidden rounded-[14px]" aria-label="用户资料卡">
            <div className="flex items-center gap-3 px-4 pb-3 pt-3.5">
                <div className="grid size-11 shrink-0 place-items-center rounded-full border border-gray-200">
                    <img className="size-10 rounded-full object-cover" src={avatar} loading="lazy" />
                </div>
                <div className="min-w-0 flex-1">
                    <div className="flex min-w-0 items-center gap-2">
                        <div className="flex flex-col gap-1">
                            <div className="truncate text-sm font-extrabold leading-5 text-slate-900" title={displayName}>
                                {displayName}
                            </div>
                            {bio && (
                                <div className="truncate text-xs leading-4 text-slate-500/90" title={bio}>
                                    {bio}
                                </div>
                            )}
                        </div>
                    </div>
                    {!isLoggedIn && (
                        <div className="mt-1 text-xs leading-4 text-slate-500/90">
                            登录后可同步词库进度与打卡数据
                        </div>
                    )}
                </div>
            </div>

            {isLoggedIn && (
                <div className="grid grid-cols-2 gap-2.5 px-4 pb-3 pt-2">
                    <div className="rounded-xl border border-slate-900/5 bg-white/65 px-2.5 py-2.5">
                        <div className="text-xs leading-4 text-slate-500/95">单词数量</div>
                        <div className="mt-1 text-lg font-black leading-[22px] text-slate-900">
                            {user?.wordNumber ?? 0}
                        </div>
                    </div>
                    <div className="rounded-xl border border-amber-500/20 bg-amber-50/90 px-2.5 py-2.5">
                        <div className="text-xs leading-4 text-slate-500/95">打卡天数</div>
                        <div className="mt-1 text-lg font-black leading-[22px] text-slate-900">
                            {user?.dayNumber ?? 0}
                        </div>
                    </div>
                </div>
            )}

            <div className="flex gap-2.5 border-t border-slate-900/5 bg-white/75 px-4 pb-3.5 pt-3">
                {!isLoggedIn ? (
                    <button
                        className="h-9 flex-1 cursor-pointer rounded-[10px] border border-blue-600/25 bg-blue-600/10 text-[13px] font-extrabold text-blue-700 transition duration-150 hover:-translate-y-0.5 hover:shadow-[0_10px_16px_rgba(15,23,42,0.10)] active:translate-y-0 active:shadow-none"
                        type="button"
                        onClick={loginHandle}
                    >
                        去登录
                    </button>
                ) : (
                    <>
                        <button
                            className="h-9 flex-1 cursor-pointer rounded-[10px] border border-slate-900/10 bg-white/90 text-[13px] font-extrabold text-slate-900/90 transition duration-150 hover:-translate-y-0.5 hover:shadow-[0_10px_16px_rgba(15,23,42,0.10)] active:translate-y-0 active:shadow-none"
                            type="button"
                            onClick={() => gotoPath('/setting/index')}
                        >
                            个人资料
                        </button>
                        <button
                            className="h-9 flex-1 cursor-pointer rounded-[10px] border border-red-500/20 bg-red-500/10 text-[13px] font-extrabold text-red-700 transition duration-150 hover:-translate-y-0.5 hover:shadow-[0_10px_16px_rgba(15,23,42,0.10)] active:translate-y-0 active:shadow-none"
                            type="button"
                            onClick={logoutHandle}
                        >
                            退出登录
                        </button>
                    </>
                )}
            </div>
        </section>
    )
}

export default Profile
